### ISSUE TITLE
Hide Weather Information until Search

### ISSUE THREAD

**Issue by davidgrieser** [DeepthiSF/WhatsTheWeatherToday#46]
When you come to the page the weather information is undefined.

This would be cleaner if that area was `hidden` from view and then displays once weather data is pulled.

**Comment by davidgrieser** [comment]
![Screen Shot 2021-08-12 at 9 10 59 AM](https://user-images.githubusercontent.com/292375/129212011-d743e84f-8282-4831-8dce-07790dd6a576.png)

Similar to this. If you feel like this is going to take longer than an hour to complete please ask for more guidance.

**Comment by DeepthiSF** [comment]
Sure David, we will work on this.
